const Data = [
  {
    name: 'Cozy Apartment',
    location: 'City Center',
    price: 1200,
    bedrooms: 2,
    bathrooms: 1,
  },
  {
    name: 'Spacious Loft',
    location: 'Suburbs',
    price: 1800,
    bedrooms: 3,
    bathrooms: 2,
  },
  {
    name: 'Luxury Penthouse',
    location: 'Downtown',
    price: 3000,
    bedrooms: 4,
    bathrooms: 3,
  },
  {
    name: 'Studio Apartment',
    location: 'Urban Area',
    price: 900,
    bedrooms: 1,
    bathrooms: 1,
  },
  {
    name: 'Country House',
    location: 'Rural Area',
    price: 2500,
    bedrooms: 5,
    bathrooms: 4,
  },
  {
    name: 'Modern Condo',
    location: 'Beachfront',
    price: 2200,
    bedrooms: 2,
    bathrooms: 2,
  },
  {
    name: 'Suburban Villa',
    location: 'Quiet Neighborhood',
    price: 2800,
    bedrooms: 4,
    bathrooms: 3,
  },
  {
    name: 'Charming Cottage',
    location: 'Countryside',
    price: 1500,
    bedrooms: 2,
    bathrooms: 1,
  },
  {
    name: 'Urban Loft',
    location: 'Downtown',
    price: 1600,
    bedrooms: 1,
    bathrooms: 1,
  },
  {
    name: 'Elegant Mansion',
    location: 'Exclusive Area',
    price: 6000,
    bedrooms: 6,
    bathrooms: 5,
  },
  {
    name: 'Cosy Cabin',
    location: 'Mountain Retreat',
    price: 1100,
    bedrooms: 2,
    bathrooms: 1,
  },
  {
    name: 'Rooftop Studio',
    location: 'Arts District',
    price: 1300,
    bedrooms: 1,
    bathrooms: 1,
  },
  {
    name: 'Ranch Style Home',
    location: 'Suburbs',
    price: 2400,
    bedrooms: 3,
    bathrooms: 2,
  },
  {
    name: 'Beach House',
    location: 'Seaside',
    price: 2800,
    bedrooms: 3,
    bathrooms: 2,
  },
  {
    name: 'Urban Oasis',
    location: 'City Center',
    price: 2000,
    bedrooms: 2,
    bathrooms: 2,
  },
  {
    name: 'Chic Townhouse',
    location: 'Historic District',
    price: 1800,
    bedrooms: 3,
    bathrooms: 2,
  },
  {
    name: 'Country Retreat',
    location: 'Rural Area',
    price: 1700,
    bedrooms: 2,
    bathrooms: 1,
  },
  {
    name: 'Modern Bungalow',
    location: 'Suburbs',
    price: 1900,
    bedrooms: 3,
    bathrooms: 2,
  },
  {
    name: 'Artistic Loft',
    location: 'Artsy Neighborhood',
    price: 1500,
    bedrooms: 1,
    bathrooms: 1,
  },
  {
    name: 'Lakefront Cottage',
    location: 'Lake District',
    price: 1300,
    bedrooms: 2,
    bathrooms: 1,
  },
 
];

export default Data;
